import type {Config} from 'tailwindcss'

export default {
    content: [
        "./pages/**/*.{js,ts,jsx,tsx}",
        "./components/**/*.{js,ts,jsx,tsx}",
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}"
    ],
    theme: {
        // colors: {
        //     "black": "#27272fff",
        //     "white": "#bdbdbd",
        //     "primary": "#594ae2ff",
        //     "primary-text": "#ffffffff",
        //     "primary-darken": "#3e2cdd",
        //     "primary-lighten": "#766ae7",
        //     "secondary": "#ff4081ff",
        //     "secondary-text": "#ffffffff",
        //     "secondary-darken": "#ff1f69",
        //     "secondary-lighten": "#ff6699",
        //     "tertiary": "#1ec8a5ff",
        //     "tertiary-text": "#ffffffff",
        //     "info": "#2196f3ff",
        //     "info-text": "#ffffffff",
        //     "info-darken": "#0c80df",
        //     "info-lighten": "#47a7f5",
        //     "success": "#00c853ff",
        //     "success-text": "#ffffffff",
        //     "success-darken": "#00a344",
        //     "success-lighten": "#00eb62",
        //     "warning": "#ff9800ff",
        //     "warning-text": "#ffffffff",
        //     "warning-darken": "#d68100",
        //     "warning-lighten": "#ffa724",
        //     "error": "#f44336ff",
        //     "error-text": "#ffffffff",
        //     "error-darken": "#f21c0d",
        //     "error-lighten": "#f66055",
        //     "dark": "#111019ff",
        //     "dark-text": "#ffffffff",
        //     "dark-darken": "#020203",
        //     "dark-lighten": "#222032",
        //     "text-primary": "#ffffffff",
        //     "text-secondary": "#92929fff",
        //     "text-disabled": "#ffffff33",
        //     "action-default": "#92929fff",
        //     "action-disabled": "#00000042",
        //     "action-disabled-background": "#ffffff1e",
        //     "surface": "#1e1e2dff",
        //     "background": "#151521ff",
        //     "background-grey": "#1a1a27ff",
        //     "drawer-background": "#151521ff",
        //     "drawer-text": "#92929fff",
        //     "drawer-icon": "#92929fff",
        //     "appbar-background": "#111019ff",
        //     "appbar-text": "#92929fff",
        //     "lines-default": "#0000001e",
        // },
        // fontFamily: {
        //     sans: ['Nunito', 'sans-serif'],
        // },
        extend: {},
    },
    plugins: [require('@headlessui/tailwindcss')],
} satisfies Config

